/* Service seam: one client per domain, mock when VITE_API_BASE is unset. */

export { datasetService } from './DatasetService'
export type { DatasetService, DatasetPatch } from './DatasetService'
export { sourceService } from './SourceService'
export type { SourceService } from './SourceService'
export { checkService } from './CheckService'
export type { CheckService } from './CheckService'
export { incidentService } from './IncidentService'
export type { IncidentService, IncidentFilter } from './IncidentService'
export { notifierService } from './NotifierService'
export type { NotifierService, NotifierInput } from './NotifierService'
export { routeService } from './RouteService'
export type { RouteService } from './RouteService'
export { statusPageService } from './StatusPageService'
export type { StatusPageService } from './StatusPageService'
export { settingsService } from './SettingsService'
export type { SettingsService, SettingsPatch } from './SettingsService'
export { tokenService } from './TokenService'
export type { TokenService } from './TokenService'
